"""exercicio 02 aula 04

Revision ID: 139bb402ebfc
Revises: fc3b1cfd8098
Create Date: 2025-12-23 15:10:41.221876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139bb402ebfc'
down_revision: Union[str, Sequence[str], None] = 'fc3b1cfd8098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
